apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: dummy-agent
  name: dummy-agent
  namespace: wazuh
spec:
  containers:
  - image: fhielpos/wazuh-agent:latest 
    name: dummy-agent
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
