apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wazuh-agent
  name: wazuh-agent
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-agent
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wazuh-agent
    spec:
      containers:
      - image: fhielpos/wazuh-agent:latest
        name: wazuh-agent
        resources: {}
        env:
          - name: WAZUH_MANAGER_IP
            value: "wazuh-remoted"
status: {}
