apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-elasticsearch
  namespace: wazuh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wazuh-elasticsearch
      type: master
  serviceName: wazuh-elasticsearch
  template:
    metadata:
      labels:
        app: wazuh-elasticsearch
        type: master
      name: wazuh-elasticsearch
    spec:
      # Set the wazuh-elasticsearch volume permissions so the elasticsearch user can use it!
      initContainers:
        - name: volume-mount-hack
          image: busybox
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          command:
            - sh
            - '-c'
            - 'chown -R 1000:1000 /usr/share/elasticsearch/data'
          volumeMounts:
            - name: wazuh-elasticsearch
              mountPath: /usr/share/elasticsearch/data
        - name: increase-the-vm-max-map-count
          image: busybox
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      containers:
        - name: wazuh-elasticsearch
          image: 'docker.elastic.co/elasticsearch/elasticsearch:7.6.2'
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
          env:
            - name: ES_JAVA_OPTS
              value: '-Xms500m -Xmx500m'
            - name: search.max_buckets
              value: "30000"
            - name: node.master
              value: 'true'
            - name: node.data
              value: 'false'
            - name: node.ingest
              value: 'false'
            - name: bootstrap.memory_lock
              value: 'false'
            - name: cluster.name
              value: wazuh
            - name: network.host
              value: 0.0.0.0
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: cluster.initial_master_nodes
              value: "wazuh-elasticsearch-0,wazuh-elasticsearch-1"
            - name: discovery.seed_hosts
              value: "wazuh-elasticsearch"
          volumeMounts:
            - name: wazuh-elasticsearch
              mountPath: /usr/share/elasticsearch/data
          ports:
            - containerPort: 9200
              name: es-rest
            - containerPort: 9300
              name: es-nodes
  volumeClaimTemplates:
    - metadata:
        name: wazuh-elasticsearch
        namespace: es-cluster
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-storage
        resources:
          requests:
            storage: 3Gi
