apiVersion: v1
kind: PersistentVolume
metadata:
  name: wazuh-elasticsearch-2
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data2"