apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-kibana
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-kibana
  serviceName: wazuh-kibana
  template:
    metadata:
      labels:
        app: wazuh-kibana
      name: wazuh-kibana
    spec:
      # Set the wazuh-kibana volume permissions so the elasticsearch user can use it!
      containers:
        - name: wazuh-kibana
          image: wazuh/wazuh-kibana:3.12.3_7.6.2
          env:
            - name: ELASTICSEARCH_HOSTS
              value: https://elasticsearch:9200
          ports:
            - containerPort: 5601
              name: kibana