apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: wazuh
  labels:
    app: wazuh-kibana
spec:
  type: LoadBalancer
  selector:
    app: wazuh-kibana
  ports:
    - name: kibana
      port: 443 
      targetPort: 5601
