apiVersion: v1
kind: Service
metadata:
  name: wazuh
  namespace: wazuh
  labels:
    app: wazuh-manager
spec:
  type: ClusterIP
  selector:
    app: wazuh-manager
    node-type: worker
  ports:
    - name: remoted
      protocol: UDP
      port: 1514
      targetPort: 1514
